name: Web App Deployment

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Infra/app/**'
      - 'Infra/ecs_app.tf'
      - 'Infra/ecr.tf'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Web App to ECS
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: eu-central-1
      TF_IN_AUTOMATION: true

    defaults:
      run:
        working-directory: Infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::760981412376:role/github-actions-terraform-role
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push web app image
        run: |
          cd app
          docker build -t case2nca-webapp .
          docker tag case2nca-webapp:latest ${{ steps.login-ecr.outputs.registry }}/case2nca-webapp:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/case2nca-webapp:latest

      - name: Deploy ECS Web App
        run: |
          terraform init -lock=false
          terraform apply -auto-approve -lock=false -target=aws_ecs_service.app_service
